hyperskill_project:
  id: 78
  ide_files: https://stepik.org/media/attachments/lesson/255033/additional_files.json
  is_template_based: false
  use_ide: true
stages:
- id: 431
  step: 7205
  is_completed: true
- id: 432
  step: 7206
  is_completed: false
- id: 433
  step: 7207
  is_completed: false
- id: 434
  step: 7208
  is_completed: false
- id: 435
  step: 7209
  is_completed: false
topics:
  1:
  - title: IDE
    theory_id: 3805
  - title: List
    theory_id: 5979
  - title: Dictionary
    theory_id: 6481
  - title: Invoking a function
    theory_id: 5891
  - title: Load module
    theory_id: 6019
  - title: Random module
    theory_id: 6263
  - title: PyCharm basics
    theory_id: 6193
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: String formatting
    theory_id: 6037
  2:
  - title: Avoiding bad comments
    theory_id: 6440
  - title: While loop
    theory_id: 5940
  - title: For loop
    theory_id: 6065
  - title: Loop control statements
    theory_id: 6302
  3:
  - title: Files
    theory_id: 6989
  - title: Intro to computational thinking
    theory_id: 8742
  - title: Components of computational thinking
    theory_id: 8745
  - title: Declaring a function
    theory_id: 5900
  - title: Arguments
    theory_id: 7248
  - title: Functional decomposition
    theory_id: 9571
  - title: Sep and end arguments of print
    theory_id: 7452
  - title: Files in Python
    theory_id: 8691
  - title: Reading files
    theory_id: 8139
  - title: Writing files
    theory_id: 8334
  - title: Flush and file arguments of print
    theory_id: 8006
  4:
  - title: Indexes
    theory_id: 6189
  - title: Slicing
    theory_id: 6177
  - title: Operations with list
    theory_id: 6031
  - title: Escape sequences
    theory_id: 7130
  - title: Basic string methods
    theory_id: 6842
  - title: Split and join
    theory_id: 6972
